name: Send Email Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # هر 5 دقیقه

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "پیام خودکار از گیت‌هاب"
          body: "سلام! این ایمیل هر ۵ دقیقه ارسال میشه."
          to: your_target_email@example.com
          from: GitHub Action <academi.mah87@gmail.com>
