name: Send Email

on:
  workflow_dispatch:  # اجرای دستی
  schedule:
    - cron: '*/5 * * * *'  # اجرای خودکار هر 5 دقیقه

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ایمیل تستی از GitHub"
          body: "سلام! این ایمیل به صورت دستی ارسال شده."
          to: your_target_email@example.com
          from: GitHub Action <academi.mah87@gmail.com>
